"""Competitor Searcher Agent Node.

Uses the Tavily API to search for competitors based on the queries
generated by the idea_parser. Assigns SRC_IDs to all discovered content
and returns raw candidates for the relevance filter.
"""

import logging
import os

from tavily import TavilyClient

from src.config.settings import get_settings
from src.graph.state import ResearchState
from src.ingestion.source_map import SourceMap

logger = logging.getLogger(__name__)


def competitor_searcher(state: ResearchState) -> dict:
    """Search for competitor candidates using Tavily.

    Args:
        state: The current ResearchState.

    Returns:
        State update dict with raw_competitor_candidates, source_map additions,
        and progress_messages.
    """
    settings = get_settings()
    parsed_idea = state["parsed_idea"]
    if not parsed_idea:
        raise ValueError("Parsed idea is missing from state.")

    queries = parsed_idea.competitor_search_terms
    depth = state.get("depth", "fast")

    # Depth settings from ARCHITECTURE.md Section 8
    # Fast: max 15 candidates total
    # Deep: max 40 candidates total
    max_total_candidates = 15 if depth == "fast" else 40

    # If fast depth, limit queries to first 2-3 (idea parser gives exactly 3)
    if depth == "fast":
        queries = queries[:3]

    results_per_query = max(1, max_total_candidates // max(1, len(queries)))

    api_key = settings.tavily_api_key or os.environ.get("TAVILY_API_KEY")
    if not api_key:
        raise ValueError("TAVILY_API_KEY is not set.")

    tavily_client = TavilyClient(api_key=api_key)

    source_map = SourceMap(existing_map=state.get("source_map", {}))
    new_sources = {}

    raw_candidates = []
    seen_urls = set()

    for query in queries:
        try:
            # Basic search, we don't need full advanced extraction here,
            # just snippets to pass to the Stage 1 relevance filter.
            response = tavily_client.search(
                query=query,
                search_depth="basic",
                max_results=results_per_query,
            )

            for result in response.get("results", []):
                url = result.get("url")
                if not url or url in seen_urls:
                    continue
                seen_urls.add(url)

                title = result.get("title", "")
                snippet = result.get("content", "")

                # Add to source map
                src_id = source_map.add(
                    url=url,
                    title=title,
                    snippet=snippet,
                    source_type="web",
                )

                # We collect only the new sources added in this node
                # because the state reducer is merge_dicts.
                new_sources[src_id] = source_map.get(src_id)

                raw_candidates.append({
                    "src_id": src_id,
                    "title": title,
                    "snippet": snippet,
                    "url": url, # Kept for debugging/display, but LLM only sees src_id
                })

                if len(raw_candidates) >= max_total_candidates:
                    break

        except Exception as e:
            # Log and continue if a single search fails
            logger.warning("Tavily search failed for query '%s': %s", query, e)

        if len(raw_candidates) >= max_total_candidates:
            break

    return {
        "raw_competitor_candidates": raw_candidates,
        "source_map": new_sources,
        "progress_messages": [
            f"Found {len(raw_candidates)} competitor candidates "
            f"across {len(queries)} queries."
        ],
    }
