"""Pain Point Miner Agent Node.

Uses Tavily (general and site:reddit.com) and the HN Algolia API to search
for user complaints, frustrations, and discussions based on the pain point
search terms generated by the idea_parser. Assigns SRC_IDs and returns
raw candidates for the relevance filter.
"""

import logging
import os

import httpx
from bs4 import BeautifulSoup
from tavily import TavilyClient

from src.config.settings import get_settings
from src.graph.state import ResearchState
from src.ingestion.source_map import SourceMap

logger = logging.getLogger(__name__)


def _strip_html(text: str) -> str:
    """Strip HTML tags from text (e.g. HN comment_text which contains <p>, <a>, etc.)."""
    if not text:
        return text
    soup = BeautifulSoup(text, "html.parser")
    return soup.get_text(separator=" ", strip=True)


def pain_point_miner(state: ResearchState) -> dict:
    """Search for pain point candidates across Web, Reddit, and Hacker News.

    Args:
        state: The current ResearchState.

    Returns:
        State update dict with raw_pain_point_candidates, source_map additions,
        and progress_messages.
    """
    settings = get_settings()
    parsed_idea = state["parsed_idea"]
    if not parsed_idea:
        raise ValueError("Parsed idea is missing from state.")

    queries = parsed_idea.pain_point_search_terms
    depth = state.get("depth", "fast")

    # Depth settings from ARCHITECTURE.md Section 8
    max_total_candidates = 15 if depth == "fast" else 40
    if depth == "fast":
        queries = queries[:3]

    # Distribute candidates roughly equally across the 3 sources (Web, Reddit, HN)
    candidates_per_source = max_total_candidates // 3
    results_per_query = max(1, candidates_per_source // max(1, len(queries)))

    api_key = settings.tavily_api_key or os.environ.get("TAVILY_API_KEY")
    if not api_key:
        raise ValueError("TAVILY_API_KEY is not set.")

    tavily_client = TavilyClient(api_key=api_key)
    source_map = SourceMap(existing_map=state.get("source_map", {}))
    new_sources = {}

    raw_candidates = []
    seen_urls = set()

    def add_candidate(url: str, title: str, snippet: str, source_type: str):
        if not url or url in seen_urls:
            return
        seen_urls.add(url)

        src_id = source_map.add(
            url=url,
            title=title,
            snippet=snippet,
            source_type=source_type,  # type: ignore
        )
        new_sources[src_id] = source_map.get(src_id)

        raw_candidates.append({
            "src_id": src_id,
            "title": title,
            "snippet": snippet,
            "url": url,
        })

    # 1. Tavily General Search
    for query in queries:
        try:
            response = tavily_client.search(
                query=query,
                search_depth="basic",
                max_results=results_per_query,
            )
            for result in response.get("results", []):
                add_candidate(
                    result.get("url"), result.get("title", ""),
                    result.get("content", ""), "web",
                )
        except Exception as e:
            logger.warning("Tavily general search failed for '%s': %s", query, e)

    # 2. Tavily Community Search
    for community in getattr(parsed_idea, "target_communities", []):
        for query in queries:
            community_query = f"{query} site:{community}"
            try:
                response = tavily_client.search(
                    query=community_query,
                    search_depth="basic",
                    max_results=results_per_query,
                )
                for result in response.get("results", []):
                    add_candidate(
                        result.get("url"), result.get("title", ""),
                        result.get("content", ""), "web",
                    )
            except Exception as e:
                logger.warning("Tavily community search failed for '%s': %s", community_query, e)

    # Truncate if we somehow exceeded max
    raw_candidates = raw_candidates[:max_total_candidates]

    return {
        "raw_pain_point_candidates": raw_candidates,
        "source_map": new_sources,
        "progress_messages": [
            f"Found {len(raw_candidates)} pain point candidates "
            f"across Web and dynamic communities."
        ],
    }
